### ISSUE TITLE
Why does a plugin fail to load?

### ISSUE THREAD

**Issue by kwhitejr** [Nordstrom/artillery-plugin-cloudwatch#16]
I'm trying to acquire more granular metrics from this plugin. When invoking the load generator I get the error `WARNING: plugin cloudwatch specified but module artillery-plugin-cloudwatch could not be loaded`, but no further context.

Steps to Reproduce
Based on @itkq work [here](https://github.com/itkq/artillery-plugin-cloudwatch/blob/master/lib/cloudwatch.js), I [forked this repo](https://github.com/kwhitejr/artillery-plugin-cloudwatch) and included his updates.

For installation, I point directly to git hash, i.e.
```
"dependencies": {
    "@nike/aaa-node-async": "^6.2.0",
    "artillery": "git+https://github.com/Nordstrom/artillery.git#25852a11f5f559fc11076314c086ae40ee129348",
    "artillery-plugin-cloudwatch": "git+https://github.com/kwhitejr/artillery-plugin-cloudwatch.git#8ac118716cca0f64b137c376195890477d058e06",
    "js-yaml": "^3.13.1",
    "lodash.merge": "^4.6.2",
    "lodash.omit": "^4.5.0",
    "util-promisify": "^2.1.0"
}
```

Installation appears fine because there is no `npm` error locally or upon deploy. 

However, when the load generator lambda runs (whether from cron job or local invocation), I received the above-described log: `WARNING: plugin cloudwatch specified but module artillery-plugin-cloudwatch could not be loaded`.

Per [this discussion](https://github.com/Nordstrom/artillery-plugin-influxdb/issues/14#issuecomment-342656223), (1) I've checked the script.yml for errors but it is clean; it will run with default `artillery-plugin-cloudwatch`; and (2) there are no other error logs, so I don't believe that it is an issue of validation.

**Comment by gwsii** [comment]
Addressed this problem over in the [Serverless Artillery repo](https://github.com/Nordstrom/serverless-artillery/issues/270). Closing.
